POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhcGFuaSIsImlkIjoiNjg2OTc0NTljNzkyZTFlNjA4YmNiMzAyIiwiaWF0IjoxNzUxNzQxNTMyLCJleHAiOjE3NTE3NDUxMzJ9.LFEN1yAcpC0kZOOXBN-MG2kLVzSb2Zsd2_dh4Ex1tPw

{
    "title": "Test12",
    "author": "Testaaja",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html"
}
